---
title: "Explore GTFS Data"
format: html
---

```{r libraries}
library(here)
library(tidyverse)
library(tidytransit)
```
# Read GTFS Feed

Use TidyTransit to read LA Metro's GTFS data from: https://gitlab.com/LACMTA/gtfs_rail/raw/master/gtfs_rail.zip?1729758603.3193846

```{r}
la_metro = read_gtfs("https://gitlab.com/LACMTA/gtfs_rail/raw/master/gtfs_rail.zip")

summary(la_metro)
```

Routes

```{r}
la_metro$routes
```

Stops

```{r}
head(la_metro$stops)
```

Stop Times

```{r}
head(la_metro$stop_times)
```

Trips

```{r}
head(la_metro$trips)
```

Use `gtfs_as_sf` to convert GTFS data to `sf` objects

```{r}
la_metro_shapes = gtfs_as_sf(la_metro)

summary(la_metro_shapes)
```
What is the structure of the `shapes` object?

```{r}
la_metro_shapes$shapes
```

Using `{tmap}` to plot the shapes

```{r}
library(tmap)
library(sf)

# Need to join shapes to trips to routes for route color
shapes_joined = la_metro_shapes$shapes |> 
  left_join(distinct(la_metro_shapes$trips, shape_id, route_id), by = "shape_id") |> 
  left_join(select(la_metro_shapes$routes, route_id, route_color), by = "route_id") |> 
  mutate(route_color = str_c("#", route_color))

shapes_joined_buffer= st_buffer(shapes_joined, 1000)

map_routes = tm_shape(shapes_joined) +
  tm_lines(col = "route_color")

```

```{r}
map_buffer = tm_shape(shapes_joined_buffer) +
  # tm_lines(col = "route_color")+
  tm_polygons(col = "route_color", alpha = .5)

map_buffer + map_routes
  
```


```{r}
ggplot(la_metro_shapes$shapes) +
  geom_sf() +
  theme_minimal()
```
```{r}
la_metro_shapes$stops |> glimpse()
```

